apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-forecast-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-forecast-api
  template:
    metadata:
      labels:
        app: weather-forecast-api
    spec:
      containers:
        - name: weather-forecast-api
          image: gubendiren/weather_forecast_api:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
