version: "3.4"

services:
  weather_forecast_web:
    image: ${DOCKER_REGISTRY-}weather_forecast_web
    build:
      context: ./weather_forecast_web
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - weather_forecast_api
  weather_forecast_api:
    image: ${DOCKER_REGISTRY-}weather_forecast_api
    build:
      context: ./WeatherForecastApi
      dockerfile: Dockerfile
    ports:
      - "8002:80"
