version: "3.4"

services:
  weather_forecast_api:
    image: ${DOCKER_REGISTRY-}weather_forecast_api
    build:
      context: .
      dockerfile: WeatherForecastApi/Dockerfile
    ports:
      - "8001:80"

  weather_forecast_web:
    image: ${DOCKER_REGISTRY-}weather_forecast_web
    build:
      context: .
      dockerfile: weather_forecast_web/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - weather_forecast_api
