apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-forecast-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-forecast-web
  template:
    metadata:
      labels:
        app: weather-forecast-web
    spec:
      containers:
        - name: weather-forecast-web
          image: gubendiren/weather_forecast_web:1.1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
